version: "3.8"
services:
  shortener:
    container_name: shortener
    build: ./
    command: ./shortener
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - CONFIG_PATH=./configs/config.yml
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local